version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "snyk"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
