name: Add new issues and pull requests to Origami Project Board
on:
  - issues
  - pull_request_target
  - pull_request

jobs:
  origami_project_board_job:
    runs-on: ubuntu-latest
    name: Add new issue or pull request to Origami Project Board
    steps:
      - name: Add new issue or pull request to Origami Project Board
        id: origami-project-board
        uses: Financial-Times/origami-project-board-action@v1
        with:
          origami-fox-access-token: ${{ secrets.ORIGAMI_FOX_ACCESS_TOKEN }}
