name: Release Origami Component
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install --only=dev
    - run: npx origami-ci release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}