name: Test Origami Component
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x
    - run: npm install -g npm@^7
    - run: npm install -g origami-build-tools@prerelease
    - run: obt install
      continue-on-error: true
    - run: obt verify
      continue-on-error: true
    - run: obt test
      continue-on-error: true
